#
###################################
# Site wide configuration
####################################
#
title: fhestvang 
email: frederikhestvang@gmail.com
description: Website of Frederik Hestvang 
url: //frederikhestvang.github.io
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Copenhagen
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: fhestvang
  avatar: #leonids-logo.png
  job: "data enthusiast"
  bio: "Feel free to reach out"
  email: "frederikhestvang@gmail.com"
  disqus-shortname: 'frederikhestvang'
  twitter: "fhestvang"
  facebook: #username
  google:
    tag_manager:
      container_id: "GTM-PP8J8TR"
  bing-verify:
  github: "frederikhestvang"
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: "frederik-hye-hestvang-121479106"
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username

  plugins: 
    - jekyll-admin
    - jekyll-twitter-plugin


